-- provides mostly glyphs as available in font NotoSans Nerd Font

--- @class Icons
return {

    arrow = "  →  ",
    arrow_bare = "→",
    arrow_down = "  ↓  ",
    arrow_down_bare = "↓",
    arrow_left = "  ←  ",
    arrow_left_bare = "←",
    arrow_up = "  ↑  ",
    arrow_up_bare = "↑",
    arrow_compact = " → ",
    arrow_double = "  ↔  ",
    arrow_double_bare = "↔",
    bullet = "  •  ",
    bullet_bare = "•",
    separator = "  •  ",
    enter = "⮠",
    first = "▕◁",
    last = "▷▏",
    next = "▷",
    previous = "◁",
    first_bare = "◁",
    last_bare = "▷",
    next_bare = "▷",
    previous_bare = "◁",

    active_tab = "\u{E98C}\u{2002}", -- massive right arrow
    active_tab_bare = "\u{E98C}",
    active_tab_minimal = "•\u{2002}",
    active_tab_minimal_bare = "•",
    back = "\u{E75A}\u{2002}", -- NW arrow;
    back_bare = "\u{E75A}",
    book = "\u{E28B}\u{2002}", -- empty book
    book_bare = "\u{E28B}",
    checkbox = "\u{E834}\u{2002}", -- ECE0 checkbox round open, F00C checkmark,  E82B, E82C ,  E833,  E834, F046 checkmark in rectangle, F05D OK circle
    checkbox_bare = "\u{E834}",
    checkmark = "\u{F00C}\u{2002}", -- ✓
    checkmark_bare = "\u{F00C}",
    clipboard = "\u{E84C}\u{2002}",
    clipboard_bare = "\u{E84C}",
    clock = "\u{EC1A}\u{2002}", -- E71F alarm, EC1A chrono 1 button, F250 hour glass (zandloper) open (see icon hourglass below), clock F43A, small clock E38A
    clock_bare = "\u{EC1A}",
    clock_minutes = "⌚\u{2002}", -- this is the clock icon as used in the stock ReaderFooter
    clock_minutes_bare = "⌚",
    copy = "\u{E88E}\u{2002}", --  clipboard E84C, E890 content duplicate
    copy_bare = "\u{E88E}",
    edit = "\u{F044}\u{2002}", -- pencil in checkbox
    edit_bare = "\u{F044}",
    erase = "\u{F014}\u{2002}", -- recycle bin
    erase_bare = "\u{F014}",
    file_open = "\u{F016}\u{2002}",
    file_open_bare = "\u{F016}",
    filter_bare = "\u{E932}",
    filter_reset_bare = "\u{E934}",
    history = "\u{E9D9}\u{2002}", -- clock with arrow
    history_bare = "\u{E9D9}",
    hourglass = "\u{F250}\u{2002}",
    hourglass_bare = "\u{F250}",
    introduction = "\u{EDE7}\u{2002}",
    introduction_bare = "\u{EDE7}",
    introduction_done = "\u{EDE6}\u{2002}",
    introduction_done_bare = "\u{EDE6}",
    lightning = "\u{26A1}\u{2002}",
    lightning_bare = "\u{26A1}",
    lines = "\u{F0C9}\u{2002}", -- F0C9 three lines, align justify F039, ED86 lines
    lines_bare = "\u{F0C9}",
    list = "\u{E978}\u{2002}", -- list numbers F0CB, E29A
    list_bare = "\u{E978}",
    location = "\u{EA51}", -- EED7 location with point, EA4D location marker, EA4F two location markers
    map = "\u{F278}\u{2002}", -- key ..., F212 half open book, F278 map open, F279 map closed, EA4C half open map
    map_bare = "\u{F278}",
    mark_current = "\u{F140}\u{2002}", -- E295 , E3D5 , E7B7 , E8A2 , E8A3 , F140 
    mark_current_bare = "\u{F140}",
    note_mark = "\u{F040}", -- pencil
    page = "\u{F016}\u{2002}", -- F15C closed page with lines, F15B blank closed page, F016 page outlined,  E923
    page_bare = "\u{F016}",
    page_content = "\u{E975}\u{2002}", -- E919 file document box, E969 float right, E975 format indent increase
    page_content_bare = "\u{E975}",
    pages = "\u{E7ED}\u{2002}", -- E23C pages
    pages_bare = "\u{E7ED}",
    popup = "\u{E7F6}\u{2002}", -- arrow to NE; E7F6 arrow NE, E881 balloon rectangle, E88E content copy popup
    popup_bare = "\u{E7F6}",
    paragraph = "\u{EDD6}\u{2002}", -- EDD6 paragraph, E927 boxed in P, E984 paragraph with arrow below, EBD7 step forward, ED18 buffer
    paragraph_bare = "\u{EDD6}",
    reset = "\u{EB58}\u{2002}", -- EB59 undo
    reset_bare = "\u{EB58}",
    save = "\u{F0C7}\u{2002}",
    save_bare = "\u{F0C7}",
    search = "\u{EA48}\u{2002}",
    search_bare = "\u{EA48}",
    spacer = "\u{2002}",
    star = " ☆",
    star_bare = "☆",
    star_closed = " ★",
    star_closed_bare = "★",
    user = "\u{F2C0}\u{2002}", -- user broad open
    user_bare = "\u{F2C0}",
    user_dark = "\u{F007}\u{2002}", -- user broad open
    user_dark_bare = "\u{F007}",
    xray_alias = "\u{EF23}\u{2002}",
    xray_alias_bare = "\u{EF23}",
    xray_full = "\u{E39B}\u{2002}", -- full moon
    xray_full_bare = "\u{E39B}",
    xray_half_left = "\u{E3CE}\u{2002}", -- half moon left
    xray_half_left_bare = "\u{E3CE}",
    xray_half_right = "\u{E3DC}\u{2002}", -- half moon right
    xray_half_right_bare = "\u{E3DC}",
    xray_item = "★",
    xray_partial = "\u{F140}\u{2002}", -- 
    xray_partial_bare = "\u{F140}",
    xray_link = "\u{EAE1}\u{2002}", --  F126, E765 attachment horizontal, EAE1 attachment vertical, EA38 link diagonal, EA36 link horizontal
    xray_link_bare = "\u{EAE1}",
}
